spring:
  profiles:
    active: dev
judge:
  judge-workspace-base: /judge/run
  compile-log-path: /log/compile.log
  judge-run-log-path: /log/judger.log
  judge-user: code
  judge-group: code
  judge-user-id: 11024
  judge-group-id: 11024

---
spring:
  profiles: pro
server:
  port: 80
---
spring:
  profiles: dev
server:
  port: 8080
logging:
  level:
    root: info
